/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xbxxoklhyuqxqelzykjr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhieHhva2xoeXVxeHFlbHp5a2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5OTE4NjksImV4cCI6MjA4OTU2Nzg2OX0.U-eB8lD--b-b8oCmOUBvrvRzSa9kgEm6yTHiLSsIMi8"